pipeline:

  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    restore: true
    mount:
      - .gradle/caches
      - .gradle/wrapper

  build.linux:
    image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Psnapshot=true -Pbranch=$DRONE_COMMIT_BRANCH -Pplatform=linux-x86_64
    when:
      event: [push, pull_request]

  build.linux-release:
    image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Pplatform=linux-x86_64
    when:
      event: tag

  publish-snapshot:
    image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Psnapshot=true -Pbranch=$DRONE_COMMIT_BRANCH -Pplatform=linux-x86_64 -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: push
#      branch: master

  publish-release:
    image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish  -Pplatform=linux-x86_64 -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    rebuild: true
    mount:
      - .gradle/caches
      - .gradle/wrapper
