
clone: 
  git:
    image: woodpeckerci/plugin-git
    when:
      event: tag

pipeline:

  libs.linux-x86_64:
    image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    commands:
      - ./gradlew publish -Prelease=true -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: tag

  libs.linux-arm64:
    image: docker.ci.interactive-instruments.de/cicd/openjdk-11-arm64-gcc102
    commands:
      - ./gradlew publish -Prelease=true -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: tag
