when:
  event: push

matrix:
  include:
    - platform: linux/amd64
      image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
    - platform: linux/arm64
      image: docker.ci.interactive-instruments.de/cicd/openjdk-11-arm64-gcc102
    - platform: darwin/arm64
      image: bash

platform: ${platform}

pipeline:
  publish:
    image: ${image}
    commands:
      - ./gradlew clean publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]

#  libs.linux-arm_64:
#    image: docker.ci.interactive-instruments.de/cicd/openjdk-11-arm64-gcc102
#    commands:
#      - ./gradlew clean publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
#    secrets: [ deploy_user, deploy_password]
