when:
  event: push

matrix:
  include:
    - platform: linux/amd64
      image: docker.ci.interactive-instruments.de/cicd/rhel-7-gcc73
      setup: echo
    - platform: linux/arm64
      image: docker.ci.interactive-instruments.de/cicd/openjdk-11-arm64-gcc102
      setup: echo
    - platform: darwin/arm64
      image: bash
      # override default /cache/gradle which does not exist on local
      setup: export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle

labels:
  platform: ${platform}

steps:
  publish:
    image: ${image}
    commands:
      - ${setup}
      - ./gradlew clean publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
